module(
    name = "bazel_cmake_conan_consumer_test",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "eros_forge", version = "0.1.0")
bazel_dep(name = "bazel_cmake_conan_test", version = "0.1.0")

local_path_override(
    module_name = "eros_forge",
    path = "../../..",
)

local_path_override(
    module_name = "bazel_cmake_conan_test",
    path = "../src",
)
